### PR TITLE
Add notin operator

### PR DESCRIPTION
**Pull request by SYOM29**
Add NotIn operator.

### CODE REVIEW

**Comment by cyilcode** [comment]
While we are at it, i think we might as well add an integration test to this feature as well.

**Comment by markikordahi** [comment]
Hi! I'm wondering why NotIn operator was not merged in master branch ? 
also with both In and NotIn opperand, what is the right way to pass value? 
```
new Filter
        {
            Value = "bar",
            PropertyName = ["foo", "foo2"],
            Operator = FilterOperation.In
        }
```

**Comment by SYOM29** [comment]
Hi @markikordahi. The NotIn implementation given in that pr was not correct. It was performing the notContains function instead of NotIn. That is the reason I closed the pr. Consecutively I could not find the time to address this. 

For the other question, the usage of In operator is as follows:

 new Filter
  {
      Value = "Te, Test, Testx",
      PropertyName = "Name",
      Operator = FilterOperation.In,
      CaseSensitive = caseSensitive
  }

The filter given above should generate the following query:
"(((x.Name == \"Te\") Or (x.Name == \" Test\")) Or (x.Name == \" Testx\"))"

or if case sensitivity is set to false:

"(((x.Name.ToLower() == \"te\".ToLower()) Or (x.Name.ToLower() == \" test\".ToLower())) Or (x.Name.ToLower() == \" testx\".ToLower()))"

Whenever in doubt about how the DQB will perform on a certain operation you can check our unit tests. The example I gave is from BuildFilterExpressionTests.cs ShouldConvertInOperationToMultipleEquals test case.

Hope this helps.

**Comment by markikordahi** [comment]
Thanks @SYOM29  for your quick response. 
I was expecting the in operand to generate something like (new[]{"te","Test","Testx"}.Contains(x.Name)) which should end up generating the SQL IN query.
thus for notIn to generate !(new[]{"te","Test","Testx"}.Contains(x.Name))

**Comment by SYOM29** [comment]
@markikordahi I don't know the reason behind the initial design. The solution you are proposing seems feasible to me, but it needs to be tested out. 

In terms of pr, I don't know who is in charge of managing this repository at this moment. @ardadevelioglu Can you assign someone to overview DQB? I can review it, no problem, only so that someone in the current team knows what is going on.

**Pull request closed without merging**
